/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "pure-black": "#000000",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#bcc9cd",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "outline": "#869397",
        "outline-variant": "#3d494c",
        "surface-tint": "#4cd7f6",
        "primary": "#4cd7f6",
        "on-primary": "#003640",
        "primary-container": "#06b6d4",
        "on-primary-container": "#00424f",
        "inverse-primary": "#00687a",
        "secondary": "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "tertiary": "#ffb873",
        "error": "#ffb4ab",
        "background": "#131313",
        "on-background": "#e2e2e2",
        "primary-hover": "#0891b2",
        "text-primary": "#ffffff",
        "text-secondary": "#a3a3a3",
        "text-muted": "#737373",
        "glass-base": "rgba(255, 255, 255, 0.03)",
        "glass-elevated": "rgba(255, 255, 255, 0.05)",
        "glass-recessed": "rgba(0, 0, 0, 0.55)",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "border-focus": "rgba(255, 255, 255, 0.12)",
        "border-hover": "rgba(255, 255, 255, 0.20)",
        "focus-ring": "rgba(6, 182, 212, 0.60)",
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'oled-2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.85)',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in-up': 'fadeInUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
};
